spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
#        spring.datasource.initialize: false
server:
  error:
    include-message: always
